### ISSUE TITLE
Mausoleum 0.3.1 fail to start

### ISSUE THREAD

**Issue by mgian** [mandeep/Mausoleum#2]
After a fresh install cloning the git repository and running `python setup.py install`, mausoleum-gui fail to start with this traceback:
> Traceback (most recent call last):
>   File "/bin/mausoleum-gui", line 11, in <module>
>     load_entry_point('mausoleum==0.3.1', 'console_scripts', 'mausoleum-gui')()
>   File "/usr/lib/python3.5/site-packages/mausoleum-0.3.1-py3.5.egg/mausoleum/application.py", line 445, in main
>   File "/usr/lib/python3.5/site-packages/mausoleum-0.3.1-py3.5.egg/mausoleum/application.py", line 413, in __init__
>   File "/usr/lib/python3.5/site-packages/mausoleum-0.3.1-py3.5.egg/mausoleum/application.py", line 340, in __init__
>   File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1202, in resource_filename
>     self, resource_name
>   File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1715, in get_resource_filename
>     return self._extract_resource(manager, zip_path)
>   File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1736, in _extract_resource
>     timestamp, size = self._get_date_and_size(self.zipinfo[zip_path])
> KeyError: 'mausoleum/settings.toml'

**Comment by mandeep** [comment]
Thanks for letting me know! I had forgotten to add the toml file to setup.py's package_data. 0.3.2 contains the fix for this; let me know if you still experience this error.

**Comment by mgian** [comment]
Problem solved. :+1:

**Comment by mandeep** [comment]
Thanks!
