### ISSUE TITLE
No way to control mountpoint when running open command

### ISSUE THREAD

**Issue by djmattyg007** [mandeep/Mausoleum#6]
This is valuable for when you need to ensure the tomb is opened at a specific path for one reason or another.

**Comment by mandeep** [comment]
I'll see if I can add this, but it is low priority for me. Feel free to submit a PR if it's something you really need.

**Comment by djmattyg007** [comment]
@mandeep I've submitted PR #7 which implements a new `--mountpoint` flag for the `enter` subcommand.
